Implement failing step for visiting home page
We try to visit the root (home) page, but get this error:

  undefined local variable or method `root_path' ...

This is because we haven't set up a root route yet. We'll do that next.