Add 'Remove done' button
We've specified a non-existent route, so the scenario now clicks the
button but gets an error:

  undefined local variable or method `remove_done_items_path' ...

At this point we've broken the app again, so we wouldn't normally
commit (at least on master) until we had things green again.